(autoload 'kill-char                            "killer" "" t)
(autoload 'backward-kill-char                   "killer" "" t)
(autoload 'kill-or-delete-char                  "killer" "" t)
(autoload 'backward-kill-or-delete-char         "killer" "" t)
(autoload 'backward-kill-or-delete-char-untabify "killer" "" t)
(autoload 'backward-word-or-wspace              "killer" "" t)
(autoload 'forward-word-or-wspace               "killer" "" t)
(autoload 'backward-delete-whitespace           "killer" "" t)
(autoload 'forward-delete-whitespace            "killer" "" t)
(autoload 'backward-kill-whitespace             "killer" "" t)
(autoload 'forward-kill-whitespace              "killer" "" t)
(autoload 'backward-kill-word-or-wspace         "killer" "" t)
(autoload 'kill-word-or-wspace                  "killer" "" t)
(autoload 'backward-kill-line                   "killer" "" t)
(provide 'killer-epkg-install)
